### ISSUE TITLE
This tool would help me soooo much! But, I'm having an issue. 

### ISSUE THREAD

**Issue by TronVonDoom** [sploders101/plexUtils#2]
When running `sudo gulp`, it gives me an "env" error. 

`tronvondoom@TronVonDoom-PC:~/plexUtils$ sudo gulp
[03:50:14] Requiring external module ts-node/register
[03:50:15] Using gulpfile /home/tronvondoom/plexUtils/gulpfile.ts
[03:50:15] Starting 'default'...
[03:50:15] Starting 'ts'...
[03:50:15] Starting 'sh'...
[03:50:15] Starting 'env'...
[03:50:15] Starting 'package.json'...
[03:50:15] 'env' errored after 16 ms
[03:50:15] Error: File not found with singular glob: /home/tronvondoom/plexUtils/src/.env (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/tronvondoom/plexUtils/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:467:12)
    at Glob._finish (/home/tronvondoom/plexUtils/node_modules/glob/glob.js:197:8)
    at done (/home/tronvondoom/plexUtils/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/tronvondoom/plexUtils/node_modules/glob/glob.js:688:12)
    at /home/tronvondoom/plexUtils/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/tronvondoom/plexUtils/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/tronvondoom/plexUtils/node_modules/glob/glob.js:764:12)
[03:50:15] 'default' errored after 18 ms`

Any idea of how to get around this? When installing, many items say "depreciated".

**Comment by TronVonDoom** [comment]
So, I figured  out my initial issues, but am now stalling at.....

`tronvondoom@TronVonDoom-PC:~/plexUtils$ sudo gulp
[05:39:47] Requiring external module ts-node/register
[05:39:48] Using gulpfile /home/tronvondoom/plexUtils/gulpfile.ts
[05:39:48] Starting 'default'...
[05:39:48] Starting 'ts'...
[05:39:48] Starting 'sh'...
[05:39:48] Starting 'env'...
[05:39:48] Starting 'package.json'...
[05:39:48] Finished 'package.json' after 37 ms
[05:39:50] Finished 'env' after 1.47 s
[05:39:50] Finished 'sh' after 1.47 s
[05:39:50] Finished 'ts' after 1.47 s
[05:39:50] Starting 'installDeps'...
[05:39:50] 'installDeps' errored after 13 ms
[05:39:50] Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[05:39:50] 'default' errored after 1.49 s`

**Comment by sploders101** [comment]
Sorry for the wait. I'll look into that this evening and get back to you, but I would not run gulp with sudo. You'll likely run into lots of permissions issues doing that. If necessary, I could also distribute a pre-built archive in case I'm able to make it work in a fresh install and can't figure out your issue.

**Comment by TronVonDoom** [comment]
Thanks so much for the response. 

I am still getting stuck at the `installDeps` and `default`. I've copied the terminal to a notepad. It's quite long and may shed some light on the issues. I had to run `sudo` on some since they were having permission issues otherwise.

[cmds.txt](https://github.com/sploders101/plexUtils/files/5773627/cmds.txt)

**Comment by TronVonDoom** [comment]
BTW, your tool would be very helpful! xD

![IMG_20210105_205117](https://user-images.githubusercontent.com/41256968/103723534-ebd20e00-4f97-11eb-8449-367a0bd85139.jpg)

**Comment by sploders101** [comment]
Haha, that's great! Sorry, it's been a hectic week, but things are starting to slow down. I'll look at it on my lunch break today and see what I can figure out.

**Comment by sploders101** [comment]
I'm so sorry! It really has been a little crazy lately. I looked at your issue over the weekend and couldn't replicate it, but this popped back up in my feed today and I just realized what it was moments after re-reading your message. It's trying to run yarn (it's a much faster dependency management tool for node with workspace support; you should check it out). You can either install yarn, or tell gulp to use npm instead. In gulpfile.ts, try changing `const yarn = cp.spawn("yarn", {` to `const yarn = cp.spawn("npm", ["install"], {` on line 42. Also, if you use 3 backticks instead of one, you can do multiline code blocks. Let me know if that fixes the issue or if something else is wrong. I'd also try starting fresh. Those permission issues would have stemmed from something being run with sudo before, so I'd delete the folder and start over.

**Comment by TronVonDoom** [comment]
I tried yarn and it was throwing me errors. I've gotten further since I've found out it was using the wrong yarn. Now, I get an error on the last gulp command. I have no idea what I am doing wrong.

**Comment by sploders101** [comment]
It might be that your node version is out of date. I'm running 15.2.1. I've linked to some instructions on getting a newer version on debian/ubuntu below. I believe anything over 10.x should work, but I'd go for 14.x.

https://github.com/nodesource/distributions/blob/master/README.md#debinstall

Hope this helps!

**Comment by TronVonDoom** [comment]
Awesome! I got it working now. The only other issue I am running into is that they aren't converting to .srt using vobsub2srt. I do have it installed. How did you go about install vobsub2srt?

**Comment by sploders101** [comment]
I'm at work, so I'll have to look at this later, but could you provide me with the specific error you're getting? It's been a while since I created & used this, so I don't remember exactly how it works, and an error message would go a long way to diagnosing the problem.

**Comment by TronVonDoom** [comment]
Sure thing. No rush. I truly appreciate your help through this. 

As for an error, there is no error. It just finishes with .idx and .sub files.

**Comment by sploders101** [comment]
Welp, I took a couple minutes to look and realized the lack of an error meant the wrong clause of an if statement was running. Turns out I was missing a few quotes. I've pushed a new version that should work. Try doing a `git pull` and try again.

**Comment by sploders101** [comment]
@TronVonDoom Did that fix your issue?

**Comment by TronVonDoom** [comment]
Ahhh, yes!!!! It did work!!!! Sorry about the late reply, my Plex server corrupted and I've been working to get it back up. Thankfully I had backups. 🤣

**Comment by TronVonDoom** [comment]
I was thinking that a "requirements.txt" might be helpful for other users that may run into the same issue. I may look into creating one for this project if you don't mind.

**Comment by sploders101** [comment]
No, I don't mind at all! Feel free to open a pull request
